#!/bin/bash

if [ ! -d "node_modules" ]; then
  echo "Installing dependencies"
  npm install
  echo "Finished; running gb-show"
fi

FILE=.env
if test -f "$FILE"; then
  source "$FILE" && node_modules/.bin/ts-node src/index.ts $@
else
  node_modules/.bin/ts-node src/index.ts $@
fi
